### ISSUE TITLE
Video of this talk?

### ISSUE THREAD

**Issue by hansschenker** [kuroidoruido/talks#1]
I am interested in your effort for an Angular Functional Component! Did you record your talk on this topic?

**Comment by kuroidoruido** [comment]
Sorry but there is no video for this talk. I made it for internal event with no record. I saw you create a question issue on the the corresponding repo I made for angular functional component, but I am sorry but the method I used to make this working on Angular 9 (if I remember) does not work anymore on more recent version. Some change had been made on how component are discovered by ngcc, so it's no more possible. Maybe it will be possible again in the future when I see some changes on the way Angular is working
